import pymanopt as mo
import numpy as np
from pymanopt.manifolds.manifold import Manifold
from utils_cm_hypersphere import *


class NullManifold(Manifold):
    """Null Manifold compatible with pymanopt.
    Args:
        manifold : a pymanopt manifold, embedded in a linear space E (same shape as the points of the manifold)
    Returns:
        pymanopt Manifold object : the null submanifold of E
    """

    def __init__(self, manifold):
        self._probepoint = manifold.random_point()
        super().__init__(name="Null manifold", dimension=0)
        self._npoint = np.zeros_like(self._probepoint)

    @property
    def typical_dist(self):
        return 0.0

    def projection(self, point, tangent_vector):
        return self._npoint

    def random_point(self):
        return self._npoint

    def random_tangent_vector(self, point):
        return self._npoint

    def zero_vector(self, point):
        return self._npoint

    def inner_product(self, point, tangent_vector_a, tangent_vector_b):
        return 0.0

    def norm(self, point, tangent_vector):
        return 0.0

    def dist(self, point_a, point_b):
        return 0.0

    def euclidean_to_riemannian_gradient(self, point, euclidean_gradient):
        return self._npoint

    def exp(self, point, tangent_vector):
        return self._npoint

    retraction = exp

    def log(self, point_a, point_b):
        return self._npoint

    def pair_mean(self, point_a, point_b):
        return self._npoint

    to_tangent_space = projection

    def transp(self, point_a, point_b, tangent_vector):
        return self._npoint


class LinearSubspace(Manifold):
    """Linear subspace of R^n
    Args:
        A : Stiefel matrix of shape (n,m)
    Returns:
        pymanopt Manifold object : the linear subspace of R^n generated by the columns of A
    """

    def __init__(self, A):
        self._n, self._m = A.shape
        self.A = A

        name = f"Im(A)"
        dimension = self._m
        super().__init__(name, dimension)

    @property
    def dimension(self):
        return self._dimension

    @property
    def typical_dist(self):
        raise (NotImplementedError)

    def inner_product(self, point, tangent_vector_a, tangent_vector_b):
        return np.tensordot(
            tangent_vector_a,
            tangent_vector_b,
            axes=tangent_vector_a.ndim,
        )

    def projection(self, point, tangent_vector):
        coeffs = np.dot(tangent_vector, self.A)
        proj = np.dot(self.A, coeffs)
        return proj

    to_tangent_space = projection

    def norm(self, point, tangent_vector):
        return np.sqrt(self.inner_product(point, tangent_vector, tangent_vector))

    def random_point(self):
        coeffs = np.random.randn(self._m)
        point = np.dot(self.A, coeffs)
        return point

    def random_tangent_vector(
        self, point
    ):  # pymanopt random tangent vectors must be unitary
        vector = (
            self.random_point()
        )  # points and tangent vectors leave in the same space
        return vector / self.norm(point, vector)

    def zero_vector(self, point):
        return np.zeros_like(point)

    def dist(self, point_a, point_b):
        return np.sqrt(np.linalg.norm(point_a - point_b, ord=2))

    def euclidean_to_riemannian_gradient(self, point, euclidean_gradient):
        return self.projection(point, euclidean_gradient)

    def exp(self, point, tangent_vector):
        return point + tangent_vector

    retraction = exp

    def log(self, point_a, point_b):
        return point_b - point_a

    def pair_mean(self, point_a, point_b):
        return self.exp(point_a, self.log(point_a, point_b) / 2)
